### PR TITLE
update cdsapi to 0.4.0

### PR DESCRIPTION
**Pull request by akrherz**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by akrherz** [comment]
@conda-forge/cdsapi anything additional I need to do here with this PR?

**Comment by chrisburr** [comment]
`  license: Apache 2.0` should be changed to `  license: Apache-2.0` to deal with the other linter suggestion (it's optional for now, but it's worth fixing now before it gets upgraded to an error).

**Comment by akrherz** [comment]
Sorry for all the thrashing, I have squashed the commits down, so hopefully this is in good shape now.

**Comment by ocefpaf** [comment]
I'll fix the remaining issues in the next PR. The mobile version of GitHub eluded me here.

**Pull request merged**
